import type { Metadata } from "next";
import Link from "next/link";

import { LeadForm } from "@/components/site/LeadForm";
import { RevenueSimulator } from "@/components/site/RevenueSimulator";
import { SiteFooter } from "@/components/site/SiteFooter";
import { SiteHeader } from "@/components/site/SiteHeader";

export const metadata: Metadata = { title: "Fidélité digitale pour indépendants et commerciaux", description: "WALS prépare un parcours pour les indépendants et commerciaux qui veulent construire un portefeuille de commerces autour de la fidélité digitale.", alternates: { canonical: "/partenaires/independants-commerciaux" } };

export default function IndependentPage(){
  return <><SiteHeader audience="partner"/><main><section className="subhero partner-theme"><div className="site-container subhero-grid"><div><Link className="breadcrumb" href="/partenaires">← Parcours partenaires</Link><span className="eyebrow">INDÉPENDANTS & COMMERCIAUX</span><h1>Prospectez localement. <span>Construisez votre portefeuille.</span></h1><p>Le parcours vise les profils qui veulent trouver leurs propres commerces, préparer une démonstration et proposer une offre de fidélité digitale sans avoir à développer la plateforme.</p><div className="hero-actions"><a className="primary-button" href="#contact">Présenter mon projet</a></div></div><div className="sector-hero-card"><small>LE PRINCIPE</small><strong>Vous prospectez, vous présentez, vous construisez votre offre et vous gardez la relation commerciale.</strong><span>WALS ne promet aucun niveau de revenu et ne publie aucun prix suggéré.</span></div></div></section><section className="section light-section"><div className="site-container"><div className="section-heading"><span className="eyebrow dark">UNE MÉTHODE RÉPÉTABLE</span><h2>De la rue au premier commerce actif.</h2></div><div className="three-grid"><article className="number-card"><span>01</span><h3>Identifier</h3><p>Choisir un commerce pour lequel le retour client et la fréquence ont une valeur claire.</p></article><article className="number-card"><span>02</span><h3>Démontrer</h3><p>Préparer une présentation personnalisée afin de montrer l'expérience plutôt que de vendre uniquement un discours.</p></article><article className="number-card"><span>03</span><h3>Suivre</h3><p>Centraliser prospects, offres et commerces dans le cockpit prévu pour le parcours partenaire.</p></article></div></div></section><section className="section dark-section"><div className="site-container split-section"><div><span className="eyebrow">VOTRE MODÈLE</span><h2>Le tarif que vous testez vient de vous.</h2><p>Le simulateur ne connaît ni votre marge, ni le futur coût WALS, ni vos coûts commerciaux. Il affiche uniquement un chiffre d'affaires brut théorique issu de vos propres saisies.</p></div><RevenueSimulator/></div></section><section className="section contact-section" id="contact"><div className="site-container contact-grid"><div><span className="eyebrow">VOTRE PROJET</span><h2>Présentez votre approche commerciale.</h2><p>Décrivez vos cibles et votre expérience. L'inscription aux informations de lancement est facultative.</p></div><LeadForm audience="partner"/></div></section></main><SiteFooter/></>;
}
