import type { Metadata } from "next";
import Link from "next/link";

import { RevenueSimulator } from "@/components/landing/RevenueSimulator";
import { LaunchNotifyForm } from "@/components/site/LaunchNotifyForm";
import { SiteFooter } from "@/components/site/SiteFooter";
import { SiteHeader } from "@/components/site/SiteHeader";

export const metadata: Metadata = { title: "Future fidélité digitale pour indépendants et commerciaux", description: "WALS développe un parcours pour les indépendants et commerciaux qui veulent construire un portefeuille de commerces autour de la fidélité digitale.", alternates: { canonical: "/partenaires/independants-commerciaux" } };

export default function IndependentPage(){
  return <><SiteHeader audience="partner"/><main><section className="subhero partner-theme"><div className="site-container subhero-grid"><div><Link className="breadcrumb" href="/partenaires">← Parcours partenaires</Link><span className="eyebrow">INDÉPENDANTS & COMMERCIAUX · EN DÉVELOPPEMENT</span><h1>Préparez votre prospection locale. <span>Construisez votre futur portefeuille.</span></h1><p>Le parcours n'est pas encore ouvert. Il est conçu pour les profils qui veulent demain trouver leurs propres commerces, préparer une démonstration et proposer une offre de fidélité digitale sans développer la plateforme.</p><div className="hero-actions"><a className="primary-button" href="#contact">Être prévenu du lancement</a></div></div><div className="sector-hero-card"><small>LE PRINCIPE ENVISAGÉ</small><strong>Vous prospecterez, présenterez votre offre et garderez la relation commerciale.</strong><span>Les montants du simulateur sont des exemples de revente et ne représentent pas le prix de WALS.</span></div></div></section><section className="section light-section"><div className="site-container"><div className="section-heading"><span className="eyebrow dark">UNE MÉTHODE RÉPÉTABLE</span><h2>De la rue au premier commerce actif.</h2></div><div className="three-grid"><article className="number-card"><span>01</span><h3>Identifier</h3><p>Choisir un commerce pour lequel le retour client et la fréquence ont une valeur claire.</p></article><article className="number-card"><span>02</span><h3>Démontrer</h3><p>Le futur outil doit permettre de préparer une présentation personnalisée et concrète.</p></article><article className="number-card"><span>03</span><h3>Suivre</h3><p>Le cockpit prévu centralisera prospects, offres et commerces.</p></article></div></div></section><section className="section dark-section"><div className="site-container split-section"><div><span className="eyebrow">SIMULATION</span><h2>Testez plusieurs tarifs de revente.</h2><p>29, 39, 49, 59 et 69 € sont uniquement des scénarios de simulation. Ils ne préjugent ni du futur prix WALS, ni de votre marge, ni de vos résultats.</p></div><RevenueSimulator/></div></section><section className="section contact-section" id="contact"><div className="site-container contact-grid"><div><span className="eyebrow">PROGRAMME EN PRÉPARATION</span><h2>Soyez prévenu dès l'ouverture partenaire.</h2><p>Renseignez uniquement votre email pour recevoir l'information lorsque WALS ouvrira ce parcours.</p></div><LaunchNotifyForm audience="partner"/></div></section></main><SiteFooter/></>;
}
