import type { Metadata } from "next";
import Link from "next/link";

import { LaunchNotifyForm } from "@/components/site/LaunchNotifyForm";
import { SiteFooter } from "@/components/site/SiteFooter";
import { SiteHeader } from "@/components/site/SiteHeader";

export const metadata: Metadata = { title: "Future solution de fidélité en marque blanche pour agences", description: "WALS développe un futur parcours pour les agences qui veulent ajouter la fidélité digitale à leur offre sans construire toute la technologie.", alternates: { canonical: "/partenaires/agences" } };

export default function AgenciesPage(){
  return <><SiteHeader audience="partner"/><main><section className="subhero partner-theme"><div className="site-container subhero-grid"><div><Link className="breadcrumb" href="/partenaires">← Parcours partenaires</Link><span className="eyebrow">POUR LES AGENCES · EN DÉVELOPPEMENT</span><h1>Préparez une future offre de fidélité digitale <span>pour vos clients.</span></h1><p>WALS n'est pas encore ouvert. Le parcours est conçu pour les agences qui accompagnent déjà des commerces et souhaitent demain compléter leur offre avec une brique de rétention et d'engagement.</p><div className="hero-actions"><a className="primary-button" href="#contact">Être prévenu du lancement</a></div></div><div className="sector-hero-card"><small>LE POSITIONNEMENT ENVISAGÉ</small><strong>Compléter site web, acquisition, communication ou réputation locale avec une future offre récurrente de fidélisation.</strong><span>Le niveau exact de marque blanche et les intégrations seront confirmés avant ouverture.</span></div></div></section><section className="section light-section"><div className="site-container"><div className="section-heading"><span className="eyebrow dark">POURQUOI UNE AGENCE</span><h2>Vous avez déjà la relation. WALS construit la brique produit.</h2></div><div className="three-grid"><article className="number-card"><span>01</span><h3>Clients existants</h3><p>Identifier les commerces de votre portefeuille pour lesquels la fidélisation a une valeur réelle.</p></article><article className="number-card"><span>02</span><h3>Offre complémentaire</h3><p>Préparer un positionnement fidélité à côté de vos prestations existantes.</p></article><article className="number-card"><span>03</span><h3>Suivi centralisé</h3><p>Le futur cockpit est pensé pour suivre démonstrations, offres et commerces depuis un même espace.</p></article></div></div></section><section className="section contact-section" id="contact"><div className="site-container contact-grid"><div><span className="eyebrow">PROGRAMME AGENCES EN PRÉPARATION</span><h2>Soyez prévenu dès l'ouverture.</h2><p>Il n'y a pas encore de candidature partenaire : renseignez seulement votre email pour recevoir l'information de lancement.</p></div><LaunchNotifyForm audience="partner"/></div></section></main><SiteFooter/></>;
}
