import type { Metadata } from "next";
import Link from "next/link";

import { LeadForm } from "@/components/site/LeadForm";
import { SiteFooter } from "@/components/site/SiteFooter";
import { SiteHeader } from "@/components/site/SiteHeader";

export const metadata: Metadata = { title: "Solution de fidélité en marque blanche pour agences", description: "WALS prépare un parcours pour les agences qui veulent ajouter la fidélité digitale à leur offre sans développer toute la technologie.", alternates: { canonical: "/partenaires/agences" } };

export default function AgenciesPage(){
  return <><SiteHeader audience="partner"/><main><section className="subhero partner-theme"><div className="site-container subhero-grid"><div><Link className="breadcrumb" href="/partenaires">← Parcours partenaires</Link><span className="eyebrow">POUR LES AGENCES</span><h1>Ajoutez la fidélité digitale <span>à votre offre client.</span></h1><p>Un parcours conçu pour les agences qui accompagnent déjà des commerces et veulent compléter leur offre avec une brique de rétention et d'engagement, sous leur propre positionnement commercial.</p><div className="hero-actions"><a className="primary-button" href="#contact">Présenter mon agence</a></div></div><div className="sector-hero-card"><small>LE BON POSITIONNEMENT</small><strong>Ne remplacez pas vos prestations existantes. Ajoutez une offre récurrente qui complète site web, acquisition, communication ou réputation locale.</strong><span>Le niveau exact de marque blanche et les intégrations finales seront documentés avant ouverture.</span></div></div></section><section className="section light-section"><div className="site-container"><div className="section-heading"><span className="eyebrow dark">POURQUOI UNE AGENCE</span><h2>Vous avez déjà la relation. WALS prépare la brique produit.</h2></div><div className="three-grid"><article className="number-card"><span>01</span><h3>Clients existants</h3><p>Identifier les commerces de votre portefeuille pour lesquels la fidélisation a une valeur réelle.</p></article><article className="number-card"><span>02</span><h3>Offre complémentaire</h3><p>Positionner la fidélité à côté de vos prestations, sans prétendre qu'elle remplace votre CRM, votre site ou vos campagnes.</p></article><article className="number-card"><span>03</span><h3>Suivi centralisé</h3><p>Le cockpit prévu doit permettre de suivre démonstrations, offres et commerces depuis un même espace.</p></article></div></div></section><section className="section contact-section" id="contact"><div className="site-container contact-grid"><div><span className="eyebrow">VOTRE AGENCE</span><h2>Expliquez votre activité et vos clients cibles.</h2><p>Aucun prix ni engagement partenaire n'est demandé sur cette page tant que les conditions finales ne sont pas arrêtées.</p></div><LeadForm audience="partner"/></div></section></main><SiteFooter/></>;
}
