import Link from "next/link";

import { AudienceHeader } from "@/components/landing/AudienceHeader";
import { MerchantDashboardMockup } from "@/components/landing/MerchantDashboardMockup";
import { MotionExperience } from "@/components/landing/MotionExperience";
import { Iphone, Samsung } from "@/components/landing/ProductDevices";
import { ArrowIcon, BenefitInterface, CheckIcon } from "@/components/landing/VisualInterfaces";
import { LeadForm } from "@/components/site/LeadForm";
import { SiteFooter } from "@/components/site/SiteFooter";
import { merchantFaq } from "@/lib/content";
import { sectors } from "@/lib/sectors";

export function MerchantExperience() {
  return <div className="site-shell bo-site merchant-site"><MotionExperience/><AudienceHeader audience="merchant"/><main>
    <section id="top" className="bo-hero merchant-hero" data-motion-section><div className="bo-hero-grid-bg"/><div className="bo-hero-glow bo-hero-glow-a"/><div className="bo-hero-glow bo-hero-glow-b"/><div className="site-container bo-hero-layout"><div className="bo-hero-copy" data-reveal><div className="bo-dev-note"><i/> WALS pour les commerces</div><p className="bo-overline">FIDÉLITÉ DIGITALE · RÉCOMPENSES · ENGAGEMENT</p><h1>Faites revenir vos clients. <span>Plus souvent.</span></h1><p className="bo-hero-promise">Une fidélité simple à garder. <strong>Une relation qui continue après le passage en caisse.</strong></p><p className="bo-hero-lead">WALS prépare une expérience de fidélité digitale dans le téléphone de vos clients, avec récompenses, campagnes, parrainage et suivi conçus pour les commerces de proximité.</p><div className="bo-hero-actions"><a className="bo-primary-cta" href="#contact">Parler de mon commerce <ArrowIcon/></a></div><div className="bo-proof-row"><span><CheckIcon/> Carte Wallet</span><span><CheckIcon/> Pas d'application WALS dédiée</span><span><CheckIcon/> Programme personnalisable</span></div></div>
      <div className="merchant-stage" data-reveal><Iphone/><Samsung/><div className="merchant-stage-card"><small>EXPÉRIENCE CLIENT</small><strong>La fidélité reste dans le téléphone.</strong><span>Les visuels ci-contre sont des aperçus produit animés.</span></div></div>
    </div></section>

    <section className="bo-opportunity dark-section merchant-flow" data-motion-section><div className="site-container bo-section-layout"><div className="bo-section-copy" data-reveal><p className="section-index light">01 / LE PRINCIPE</p><h2>Du premier passage <span>au prochain retour.</span></h2><p>Le programme de fidélité doit rester simple pour le client et utile pour le commerce. WALS relie l'expérience Wallet, les récompenses et les actions de réactivation.</p></div><div className="bo-opportunity-flow" data-reveal><div className="bo-flow-node is-wals"><small>PASSAGE</small><strong>CLIENT</strong></div><i>↓</i><div className="bo-flow-node is-brand"><small>FIDÉLITÉ</small><strong>WALLET</strong></div><i>↓</i><div className="bo-flow-node"><small>MOTIVATION</small><strong>RÉCOMPENSE</strong></div><i>↓</i><div className="bo-flow-node is-money"><small>OBJECTIF</small><strong>RETOUR</strong></div></div><p className="bo-opportunity-line" data-reveal>Une mécanique visible côté client. <strong>Un pilotage clair côté commerce.</strong></p></div></section>

    <section id="solutions" className="bo-benefits light-section" data-motion-section><div className="site-container"><div className="bo-heading-row" data-reveal><p className="section-index">02 / VOTRE EXPÉRIENCE</p><div><h2>Les mêmes visuels WALS. <span>Un discours adapté au commerçant.</span></h2><p>La direction artistique historique est conservée : smartphones, Wallet, roue, cartes et interfaces animées.</p></div></div><div className="bo-benefit-grid"><article className="bo-benefit-card bo-benefit-wide" data-reveal><div className="bo-benefit-copy"><span>01</span><h3>Carte de fidélité digitale</h3><p>Une carte pensée pour rester accessible dans le Wallet du client.</p><em className="bo-feature-status">Aperçu produit</em></div><div className="bo-benefit-visual bo-phone-crop"><Iphone compact/></div></article><article className="bo-benefit-card" data-reveal><div className="bo-benefit-copy"><span>02</span><h3>Parrainage</h3><p>Encourager les clients satisfaits à recommander votre commerce.</p><em className="bo-feature-status">En préparation</em></div><div className="bo-benefit-visual"><BenefitInterface type="referral"/></div></article><article className="bo-benefit-card" data-reveal><div className="bo-benefit-copy"><span>03</span><h3>Campagnes ciblées</h3><p>Créer une raison pertinente de revenir entre deux visites.</p><em className="bo-feature-status">En préparation</em></div><div className="bo-benefit-visual"><BenefitInterface type="campaign"/></div></article><article className="bo-benefit-card" data-reveal><div className="bo-benefit-copy"><span>04</span><h3>Jeux et récompenses</h3><p>Créer de l'engagement avec des expériences ludiques.</p><em className="bo-feature-status">Aperçu produit</em></div><div className="bo-benefit-visual bo-phone-crop is-play"><Samsung compact/></div></article><article className="bo-benefit-card bo-benefit-wide" data-reveal><div className="bo-benefit-copy"><span>05</span><h3>Suivi et statistiques</h3><p>Comprendre l'utilisation du programme et ajuster vos actions.</p><em className="bo-feature-status">En préparation</em></div><div className="bo-benefit-visual"><BenefitInterface type="stats"/></div></article></div></div></section>

    <section id="fonctionnement" className="bo-start dark-section" data-motion-section><div className="site-container"><div className="bo-heading-row bo-heading-light" data-reveal><p className="section-index light">03 / FONCTIONNEMENT</p><div><h2>Simple au comptoir. <span>Visible dans le téléphone.</span></h2><p>Le parcours cible évite de transformer la fidélité en opération compliquée.</p></div></div><div className="bo-start-grid"><article data-reveal><span>01</span><h3>Présentez le programme</h3><p>Un QR code permet d'accéder au parcours de fidélité.</p></article><article data-reveal><span>02</span><h3>Ajout au Wallet</h3><p>Le client conserve sa carte dans l'écosystème Wallet compatible.</p></article><article data-reveal><span>03</span><h3>Progression</h3><p>Les visites et récompenses sont matérialisées de manière claire.</p></article><article data-reveal><span>04</span><h3>Réactivation</h3><p>Le commerce prépare des actions de retour adaptées.</p></article></div></div></section>

    <section className="bo-cockpit light-section" data-motion-section><div className="site-container"><div className="bo-heading-row" data-reveal><p className="section-index">04 / VOTRE ESPACE</p><div><h2>Votre fidélité. <span>Un seul tableau de bord.</span></h2><p>Un aperçu séparé du cockpit revendeur, pensé pour les données et actions du commerce.</p></div></div><div className="bo-cockpit-frame" data-reveal><MerchantDashboardMockup/></div></div></section>

    <section id="secteurs" className="bo-markets dark-section" data-motion-section><div className="site-container"><div className="bo-heading-row bo-heading-light" data-reveal><p className="section-index light">05 / COMMERCES</p><div><h2>Une mécanique adaptée <span>à votre rythme de visite.</span></h2><p>Les pages sectorielles détaillent des cas d'usage spécifiques plutôt qu'un même programme générique.</p></div></div><div className="bo-market-grid">{sectors.map((sector,index)=><Link href={`/commercants/${sector.slug}`} key={sector.slug}><article data-reveal><span>{String(index+1).padStart(2,"0")}</span><strong>{sector.shortName}</strong><small>Voir les cas d'usage →</small></article></Link>)}</div></div></section>

    <section className="bo-faq light-section" data-motion-section><div className="site-container bo-faq-layout"><div className="bo-faq-heading" data-reveal><p className="section-index">06 / QUESTIONS</p><h2>Ce que le commerçant <span>doit savoir.</span></h2><p>Les éléments encore en développement restent explicitement présentés comme tels.</p></div><div className="bo-faq-list" data-reveal>{merchantFaq.map(([question,answer])=><details key={question}><summary>{question}<span>+</span></summary><p>{answer}</p></details>)}</div></div></section>

    <section id="contact" className="bo-final" data-motion-section><div className="bo-final-grid"/><div className="site-container bo-final-layout"><div data-reveal><div className="bo-dev-note is-light"><i/> Parcours commerce</div><h2>Voyons si WALS <span>correspond à votre commerce.</span></h2><p>Décrivez votre activité, votre fidélité actuelle et ce que vous souhaitez améliorer.</p><div className="bo-final-proof"><CheckIcon/> La demande reste distincte de l'inscription marketing facultative.</div></div><div className="bo-final-form" data-reveal><small>VOTRE COMMERCE</small><h3>Demander une présentation</h3><LeadForm audience="merchant"/></div></div></section>
  </main><SiteFooter/></div>;
}
