import { AudienceHeader } from "@/components/landing/AudienceHeader";
import { BrandMark } from "@/components/landing/BrandMark";
import { DashboardMockup } from "@/components/landing/DashboardMockup";
import { MotionExperience } from "@/components/landing/MotionExperience";
import { Iphone, Samsung } from "@/components/landing/ProductDevices";
import { RevenueSimulator } from "@/components/landing/RevenueSimulator";
import { ArrowIcon, BenefitInterface, CheckIcon, FidelyaLogo } from "@/components/landing/VisualInterfaces";
import { LaunchNotifyForm } from "@/components/site/LaunchNotifyForm";
import { SiteFooter } from "@/components/site/SiteFooter";
import { partnerFaq, partnerSupport } from "@/lib/content";

export function PartnerExperience() {
  return <div className="site-shell bo-site"><MotionExperience/><AudienceHeader audience="partner"/><main>
    <section id="top" className="bo-hero" data-motion-section><div className="bo-hero-grid-bg"/><div className="bo-hero-glow bo-hero-glow-a"/><div className="bo-hero-glow bo-hero-glow-b"/><div className="site-container bo-hero-layout"><div className="bo-hero-copy" data-reveal><div className="bo-dev-note"><i/> Ouverture prochaine du programme partenaire</div><p className="bo-overline">CRÉEZ VOTRE PROPRE ACTIVITÉ · WALS PARTENAIRES</p><h1>Construisez votre activité <span>de fidélité digitale.</span></h1><p className="bo-hero-promise">Votre marque. Vos prix. Vos clients. <strong>Notre technologie.</strong></p><p className="bo-hero-lead">WALS prépare un programme en marque blanche avec démonstrations personnalisées, outils commerciaux et cockpit partenaire pour vous permettre de construire et piloter votre propre offre.</p><div className="bo-hero-actions"><a className="bo-primary-cta" href="#ouverture">Être prévenu de l'ouverture <ArrowIcon/></a></div><div className="bo-proof-row"><span><CheckIcon/> Programme en marque blanche</span><span><CheckIcon/> Tarifs de revente libres</span><span><CheckIcon/> Cockpit partenaire dédié</span></div></div>
      <div className="bo-hero-business" data-reveal><div className="bo-hero-business-ring"/><div className="bo-brand-origin"><span>WALS</span><i>→</i><strong>VOTRE MARQUE</strong></div><article className="bo-fidelya-shell"><div className="bo-fidelya-head"><FidelyaLogo/><span>EXEMPLE DE MARQUE</span></div><div className="bo-fidelya-main"><div className="bo-fidelya-offer"><small>EXEMPLE DE TARIF DE REVENTE</small><strong>39 €<em>/mois</em></strong><span>Carte Wallet · campagnes · statistiques</span></div><div className="bo-fidelya-mini-dashboard"><div><span>Clients actifs</span><strong>18</strong></div><div className="is-revenue"><span>Revenu indicatif</span><strong>702 €</strong></div><div><span>Nouveaux ce mois</span><strong>+3</strong></div></div></div><div className="bo-fidelya-footer"><span>Simulation indicative</span><small>Technologie <b>WALS</b></small></div></article><div className="bo-wallet-demo-card"><span>LE FOURNIL</span><strong>7 / 10 tampons</strong><div>{Array.from({length:10}).map((_,index)=><i key={index} className={index<7?"on":""}>F</i>)}</div><small>Aperçu de carte</small></div></div>
    </div></section>

    <section id="business" className="bo-opportunity dark-section" data-motion-section><div className="site-container bo-section-layout"><div className="bo-section-copy" data-reveal><p className="section-index light">01 / LE MODÈLE</p><h2>Votre offre commerciale. <span>La technologie WALS.</span></h2><p>WALS prend en charge la couche technologique afin que vous puissiez vous concentrer sur votre marque, vos offres, vos prospects et vos clients.</p></div><div className="bo-opportunity-flow" data-reveal><div className="bo-flow-node is-wals"><small>TECHNOLOGIE</small><strong>WALS</strong></div><i>↓</i><div className="bo-flow-node is-brand"><small>IDENTITÉ</small><strong>VOTRE MARQUE</strong></div><i>↓</i><div className="bo-flow-node"><small>PROPOSITION</small><strong>VOTRE OFFRE</strong></div><i>↓</i><div className="bo-flow-node"><small>PORTEFEUILLE</small><strong>VOS COMMERCES</strong></div></div><p className="bo-opportunity-line" data-reveal>Vous développez votre activité. <strong>WALS opère la technologie.</strong></p></div></section>

    <section className="bo-freedom light-section" data-motion-section><div className="site-container"><div className="bo-heading-row" data-reveal><p className="section-index">02 / VOTRE LIBERTÉ</p><div><h2>Votre activité. <span>Vos règles.</span></h2><p>Les montants affichés servent à visualiser différents scénarios de revente. Ils ne correspondent pas au prix de WALS.</p></div></div><div className="bo-freedom-grid"><article data-reveal><span>01</span><h3>Votre marque</h3><p>Nom, logo, couleurs et identité commerciale selon le périmètre de personnalisation proposé.</p><div className="bo-freedom-visual bo-brand-mini"><FidelyaLogo small/></div></article><article data-reveal><span>02</span><h3>Vos offres</h3><p>Composez les services que vous souhaitez proposer aux commerces.</p><div className="bo-freedom-visual bo-offer-stack"><b>FIDÉLITÉ</b><b>PLAY</b><b>ENGAGEMENT</b></div></article><article data-reveal><span>03</span><h3>Vos prix</h3><p>Vous restez libre des tarifs facturés à vos clients.</p><div className="bo-freedom-visual bo-pricing-mini"><div><span>Exemples mensuels</span><b>29 · 39 · 49 · 59 · 69 €</b></div><div><span>Options</span><b>SELON VOTRE OFFRE</b></div><div><span>Installation</span><b>À VOTRE CHOIX</b></div></div></article><article data-reveal><span>04</span><h3>Vos clients</h3><p>Vous développez votre propre portefeuille de commerces.</p><div className="bo-freedom-visual bo-client-mini"><i>L</i><i>M</i><i>B</i><i>C</i><strong>+18</strong></div></article></div></div></section>

    <section id="revenue" className="bo-revenue dark-section" data-motion-section><div className="site-container"><div className="bo-heading-row bo-heading-light" data-reveal><p className="section-index light">03 / SIMULATEUR</p><div><h2>Testez différents <span>scénarios de revente.</span></h2><p>Sélectionnez 29, 39, 49, 59 ou 69 € puis choisissez une taille de portefeuille pour visualiser un chiffre d'affaires mensuel indicatif.</p></div></div><RevenueSimulator/></div></section>

    <section id="cockpit" className="bo-cockpit light-section" data-motion-section><div className="site-container"><div className="bo-heading-row" data-reveal><p className="section-index">04 / COCKPIT PARTENAIRE</p><div><h2>Votre business. <span>Un seul cockpit.</span></h2><p>Prospects, démonstrations, clients et revenus sont présentés avec des données d'exemple pour illustrer l'expérience partenaire.</p></div></div><div className="bo-cockpit-frame" data-reveal><DashboardMockup/></div></div></section>

    <section id="solutions" className="bo-benefits light-section" data-motion-section><div className="site-container"><div className="bo-heading-row" data-reveal><p className="section-index">05 / VOTRE OFFRE</p><div><h2>Des expériences concrètes <span>à présenter aux commerces.</span></h2><p>Prévisualisez les principales expériences de fidélité que vous pourrez intégrer à votre offre.</p></div></div><div className="bo-benefit-grid"><article className="bo-benefit-card bo-benefit-wide" data-reveal><div className="bo-benefit-copy"><span>01</span><h3>Fidélité Wallet</h3><p>Une carte digitale pensée pour l'écosystème Wallet du client.</p><em className="bo-feature-status">Aperçu produit</em></div><div className="bo-benefit-visual bo-phone-crop"><Iphone compact/></div></article><article className="bo-benefit-card" data-reveal><div className="bo-benefit-copy"><span>02</span><h3>Parrainage</h3><p>Une mécanique pour encourager et suivre les recommandations clients.</p><em className="bo-feature-status">En préparation</em></div><div className="bo-benefit-visual"><BenefitInterface type="referral"/></div></article><article className="bo-benefit-card" data-reveal><div className="bo-benefit-copy"><span>03</span><h3>Campagnes</h3><p>Des communications conçues pour soutenir le retour client.</p><em className="bo-feature-status">En préparation</em></div><div className="bo-benefit-visual"><BenefitInterface type="campaign"/></div></article><article className="bo-benefit-card" data-reveal><div className="bo-benefit-copy"><span>04</span><h3>Play</h3><p>Roue digitale et récompenses pour enrichir l'expérience de fidélité.</p><em className="bo-feature-status">Aperçu produit</em></div><div className="bo-benefit-visual bo-phone-crop is-play"><Samsung compact/></div></article><article className="bo-benefit-card bo-benefit-wide" data-reveal><div className="bo-benefit-copy"><span>05</span><h3>Statistiques</h3><p>Des indicateurs pour mieux piloter la fidélité et la relation client.</p><em className="bo-feature-status">En préparation</em></div><div className="bo-benefit-visual"><BenefitInterface type="stats"/></div></article></div></div></section>

    <section id="how" className="bo-start dark-section" data-motion-section><div className="site-container"><div className="bo-heading-row bo-heading-light" data-reveal><p className="section-index light">06 / PARCOURS COMMERCIAL</p><div><h2>Du premier prospect <span>au premier client.</span></h2><p>Un parcours structuré pour avancer commerce après commerce.</p></div></div><div className="bo-start-grid"><article data-reveal><span>01</span><h3>Personnaliser votre identité</h3><p>Préparer votre marque et votre positionnement.</p></article><article data-reveal><span>02</span><h3>Créer une démo</h3><p>Présenter une expérience adaptée au prospect.</p></article><article data-reveal><span>03</span><h3>Prospecter</h3><p>Identifier les commerces pertinents autour de vous.</p></article><article data-reveal><span>04</span><h3>Présenter</h3><p>S'appuyer sur une démonstration concrète.</p></article><article data-reveal><span>05</span><h3>Fixer votre offre</h3><p>Déterminer vos propres conditions et tarifs de revente.</p></article><article data-reveal><span>06</span><h3>Gérer votre client</h3><p>Centraliser le suivi depuis votre cockpit partenaire.</p></article></div></div></section>

    <section className="bo-white-label dark-section" data-motion-section><div className="site-container"><div className="bo-heading-row bo-heading-light" data-reveal><p className="section-index light">07 / MARQUE BLANCHE</p><div><h2>Votre marque devant. <span>WALS derrière.</span></h2><p>Le programme est conçu pour placer votre identité au premier plan. Le périmètre précis de personnalisation sera détaillé lors de l'ouverture du programme partenaire.</p></div></div><div className="bo-white-label-grid" data-reveal><div className="bo-side-card is-you"><small>VOUS</small><FidelyaLogo/><ul><li>Votre identité</li><li>Vos offres</li><li>Vos prix</li><li>Vos prospects</li><li>Vos clients</li><li>Votre relation commerciale</li></ul></div><div className="bo-white-label-center"><span>VOUS VENDEZ</span><i>↔</i><strong>WALS OPÈRE</strong></div><div className="bo-side-card is-wals"><small>WALS</small><BrandMark/><ul><li>Technologie</li><li>Wallet</li><li>Infrastructure</li><li>Hébergement</li><li>Outils</li><li>Mises à jour</li></ul></div></div></div></section>

    <section className="bo-freedom light-section" data-motion-section><div className="site-container"><div className="bo-heading-row" data-reveal><p className="section-index">08 / ACCOMPAGNEMENT</p><div><h2>Des outils prévus pour <span>mieux vendre.</span></h2><p>Démonstrations, supports, formation et accompagnement sont prévus pour faciliter le lancement et le développement de votre activité.</p></div></div><div className="bo-freedom-grid">{partnerSupport.map((item,index)=><article key={item.title} data-reveal><span>0{index+1}</span><h3>{item.title}</h3><p>{item.description}</p><em className="bo-feature-status">En préparation</em></article>)}</div></div></section>

    <section className="bo-faq light-section" data-motion-section><div className="site-container bo-faq-layout"><div className="bo-faq-heading" data-reveal><p className="section-index">09 / QUESTIONS</p><h2>Préparez votre activité. <span>WALS prépare l'ouverture.</span></h2><p>Retrouvez les principales réponses sur le programme partenaire.</p></div><div className="bo-faq-list" data-reveal>{partnerFaq.map(([question,answer])=><details key={question}><summary>{question}<span>+</span></summary><p>{answer}</p></details>)}</div></div></section>

    <section id="ouverture" className="bo-final" data-motion-section><div className="bo-final-grid"/><div className="site-container bo-final-layout"><div data-reveal><div className="bo-dev-note is-light"><i/> Ouverture prochaine</div><h2>Soyez prévenu <span>dès l'ouverture partenaire.</span></h2><p>Laissez simplement votre adresse email pour recevoir l'information dès que le programme partenaire WALS sera disponible.</p><div className="bo-final-proof"><CheckIcon/> Une inscription suffit pour être prévenu de l'ouverture.</div></div><div className="bo-final-form" data-reveal><small>OUVERTURE WALS · PARTENAIRES</small><h3>Me prévenir de l'ouverture</h3><LaunchNotifyForm audience="partner"/></div></div></section>
  </main><SiteFooter/></div>;
}
