import { AudienceHeader } from "@/components/landing/AudienceHeader";
import { BrandMark } from "@/components/landing/BrandMark";
import { DashboardMockup } from "@/components/landing/DashboardMockup";
import { MotionExperience } from "@/components/landing/MotionExperience";
import { Iphone, Samsung } from "@/components/landing/ProductDevices";
import { RevenueSimulator } from "@/components/landing/RevenueSimulator";
import { ArrowIcon, BenefitInterface, CheckIcon, FidelyaLogo } from "@/components/landing/VisualInterfaces";
import { LeadForm } from "@/components/site/LeadForm";
import { SiteFooter } from "@/components/site/SiteFooter";
import { partnerFaq, partnerSupport } from "@/lib/content";

export function PartnerExperience() {
  return <div className="site-shell bo-site"><MotionExperience/><AudienceHeader audience="partner"/><main>
    <section id="top" className="bo-hero" data-motion-section><div className="bo-hero-grid-bg"/><div className="bo-hero-glow bo-hero-glow-a"/><div className="bo-hero-glow bo-hero-glow-b"/><div className="site-container bo-hero-layout"><div className="bo-hero-copy" data-reveal><div className="bo-dev-note"><i/> Accès partenaires en préparation</div><p className="bo-overline">CRÉEZ VOTRE PROPRE ACTIVITÉ · PROPULSÉE PAR WALS</p><h1>Lancez votre propre business <span>de fidélité digitale.</span></h1><p className="bo-hero-promise">Votre marque. Vos prix. Vos clients. <strong>Notre technologie.</strong></p><p className="bo-hero-lead">Retrouvez le positionnement historique WALS : construisez votre offre, préparez vos démos, prospectez les commerces et pilotez votre portefeuille depuis un cockpit dédié.</p><div className="bo-hero-actions"><a className="bo-primary-cta" href="#ouverture">Demander l'accès partenaire <ArrowIcon/></a></div><div className="bo-proof-row"><span><CheckIcon/> Marque blanche en préparation</span><span><CheckIcon/> Vous fixez vos prix</span><span><CheckIcon/> Votre relation commerciale</span></div></div>
      <div className="bo-hero-business" data-reveal><div className="bo-hero-business-ring"/><div className="bo-brand-origin"><span>WALS</span><i>→</i><strong>VOTRE MARQUE</strong></div><article className="bo-fidelya-shell"><div className="bo-fidelya-head"><FidelyaLogo/><span>EXEMPLE DE MARQUE</span></div><div className="bo-fidelya-main"><div className="bo-fidelya-offer"><small>FIDÉLITÉ DIGITALE</small><strong className="price-placeholder">VOTRE TARIF<em>/mois</em></strong><span>Carte Wallet · campagnes · statistiques</span></div><div className="bo-fidelya-mini-dashboard"><div><span>Clients actifs</span><strong>—</strong></div><div className="is-revenue"><span>Tarification</span><strong>Libre</strong></div><div><span>Nouveaux</span><strong>—</strong></div></div></div><div className="bo-fidelya-footer"><span>Votre marque devant.</span><small>Technologie <b>WALS</b></small></div></article><div className="bo-wallet-demo-card"><span>LE FOURNIL</span><strong>7 / 10 tampons</strong><div>{Array.from({length:10}).map((_,index)=><i key={index} className={index<7?"on":""}>F</i>)}</div><small>Carte de démonstration</small></div></div>
    </div></section>

    <section id="business" className="bo-opportunity dark-section" data-motion-section><div className="site-container bo-section-layout"><div className="bo-section-copy" data-reveal><p className="section-index light">01 / L'OPPORTUNITÉ</p><h2>Votre offre commerciale. <span>Notre infrastructure.</span></h2><p>WALS est pensé pour vous éviter de développer la couche technologique. Vous vous concentrez sur votre marque, vos offres, vos prospects et vos clients.</p></div><div className="bo-opportunity-flow" data-reveal><div className="bo-flow-node is-wals"><small>TECHNOLOGIE</small><strong>WALS</strong></div><i>↓</i><div className="bo-flow-node is-brand"><small>IDENTITÉ</small><strong>VOTRE MARQUE</strong></div><i>↓</i><div className="bo-flow-node"><small>PROPOSITION</small><strong>VOTRE OFFRE</strong></div><i>↓</i><div className="bo-flow-node"><small>PORTEFEUILLE</small><strong>VOS COMMERCES</strong></div></div><p className="bo-opportunity-line" data-reveal>Vous développez votre activité. <strong>WALS fait fonctionner la technologie.</strong></p></div></section>

    <section className="bo-freedom light-section" data-motion-section><div className="site-container"><div className="bo-heading-row" data-reveal><p className="section-index">02 / VOTRE LIBERTÉ</p><div><h2>Votre activité. <span>Vos règles.</span></h2><p>Aucun prix fictif n'est imposé : vous construisez votre proposition commerciale.</p></div></div><div className="bo-freedom-grid"><article data-reveal><span>01</span><h3>Votre marque</h3><p>Nom, logo, couleurs et identité commerciale.</p><div className="bo-freedom-visual bo-brand-mini"><FidelyaLogo small/></div></article><article data-reveal><span>02</span><h3>Vos offres</h3><p>Composez les services que vous souhaitez proposer.</p><div className="bo-freedom-visual bo-offer-stack"><b>FIDÉLITÉ</b><b>PLAY</b><b>ENGAGEMENT</b></div></article><article data-reveal><span>03</span><h3>Vos prix</h3><p>Vous choisissez les tarifs facturés à vos clients.</p><div className="bo-freedom-visual bo-pricing-mini"><div><span>Abonnement</span><b className="price-free">LIBRE</b></div><div><span>Options</span><b>SELON VOTRE OFFRE</b></div><div><span>Installation</span><b>À VOTRE CHOIX</b></div></div></article><article data-reveal><span>04</span><h3>Vos clients</h3><p>Vous développez votre propre portefeuille de commerces.</p><div className="bo-freedom-visual bo-client-mini"><i>L</i><i>M</i><i>B</i><i>C</i><strong>+</strong></div></article></div></div></section>

    <section id="revenue" className="bo-revenue dark-section" data-motion-section><div className="site-container"><div className="bo-heading-row bo-heading-light" data-reveal><p className="section-index light">03 / SIMULATEUR</p><div><h2>Testez votre propre <span>modèle commercial.</span></h2><p>Saisissez votre tarif et le nombre de commerces envisagé. WALS ne suggère aucun prix de revente.</p></div></div><RevenueSimulator/></div></section>

    <section id="cockpit" className="bo-cockpit light-section" data-motion-section><div className="site-container"><div className="bo-heading-row" data-reveal><p className="section-index">04 / VOTRE COCKPIT</p><div><h2>Votre business. <span>Un seul cockpit.</span></h2><p>Prospects, démos, clients et actions commerciales dans une interface qui reprend exactement l'univers visuel WALS.</p></div></div><div className="bo-cockpit-frame" data-reveal><DashboardMockup/></div></div></section>

    <section id="solutions" className="bo-benefits light-section" data-motion-section><div className="site-container"><div className="bo-heading-row" data-reveal><p className="section-index">05 / CE QUE VOUS VENDEZ</p><div><h2>Des expériences concrètes <span>à montrer aux commerces.</span></h2><p>Les mêmes smartphones, animations Wallet et visuels de démonstration que la direction artistique historique.</p></div></div><div className="bo-benefit-grid"><article className="bo-benefit-card bo-benefit-wide" data-reveal><div className="bo-benefit-copy"><span>01</span><h3>Fidélité Wallet</h3><p>Une carte digitale directement dans l'écosystème Wallet du client.</p><em className="bo-feature-status">Aperçu produit</em></div><div className="bo-benefit-visual bo-phone-crop"><Iphone compact/></div></article><article className="bo-benefit-card" data-reveal><div className="bo-benefit-copy"><span>02</span><h3>Parrainage</h3><p>Une mécanique simple à présenter et à configurer.</p><em className="bo-feature-status">En préparation</em></div><div className="bo-benefit-visual"><BenefitInterface type="referral"/></div></article><article className="bo-benefit-card" data-reveal><div className="bo-benefit-copy"><span>03</span><h3>Campagnes</h3><p>Des communications pour soutenir le retour client.</p><em className="bo-feature-status">En préparation</em></div><div className="bo-benefit-visual"><BenefitInterface type="campaign"/></div></article><article className="bo-benefit-card" data-reveal><div className="bo-benefit-copy"><span>04</span><h3>Play</h3><p>Roue digitale et récompenses pour créer de l'engagement.</p><em className="bo-feature-status">Aperçu produit</em></div><div className="bo-benefit-visual bo-phone-crop is-play"><Samsung compact/></div></article><article className="bo-benefit-card bo-benefit-wide" data-reveal><div className="bo-benefit-copy"><span>05</span><h3>Statistiques</h3><p>Des indicateurs destinés à mieux piloter la fidélité.</p><em className="bo-feature-status">En préparation</em></div><div className="bo-benefit-visual"><BenefitInterface type="stats"/></div></article></div></div></section>

    <section id="how" className="bo-start dark-section" data-motion-section><div className="site-container"><div className="bo-heading-row bo-heading-light" data-reveal><p className="section-index light">06 / DÉMARRER</p><div><h2>Du premier prospect <span>au premier client.</span></h2><p>Un parcours commercial pensé pour être répété commerce après commerce.</p></div></div><div className="bo-start-grid"><article data-reveal><span>01</span><h3>Personnalisez votre identité</h3><p>Préparez votre marque et votre positionnement.</p></article><article data-reveal><span>02</span><h3>Créez une démo</h3><p>Montrez une expérience adaptée au prospect.</p></article><article data-reveal><span>03</span><h3>Prospectez</h3><p>Trouvez les commerces pertinents autour de vous.</p></article><article data-reveal><span>04</span><h3>Présentez</h3><p>Appuyez-vous sur une démo concrète.</p></article><article data-reveal><span>05</span><h3>Fixez votre offre</h3><p>Déterminez vos propres conditions et tarifs.</p></article><article data-reveal><span>06</span><h3>Gérez votre client</h3><p>Centralisez le suivi depuis votre cockpit.</p></article></div></div></section>

    <section className="bo-white-label dark-section" data-motion-section><div className="site-container"><div className="bo-heading-row bo-heading-light" data-reveal><p className="section-index light">07 / MARQUE BLANCHE</p><div><h2>Votre marque devant. <span>WALS derrière.</span></h2><p>Le niveau exact de marque blanche reste à valider techniquement avant engagement contractuel.</p></div></div><div className="bo-white-label-grid" data-reveal><div className="bo-side-card is-you"><small>VOUS</small><FidelyaLogo/><ul><li>Votre identité</li><li>Vos offres</li><li>Vos prix</li><li>Vos prospects</li><li>Vos clients</li><li>Votre relation commerciale</li></ul></div><div className="bo-white-label-center"><span>VOUS VENDEZ</span><i>↔</i><strong>WALS OPÈRE</strong></div><div className="bo-side-card is-wals"><small>WALS</small><BrandMark/><ul><li>Technologie</li><li>Wallet</li><li>Infrastructure</li><li>Hébergement</li><li>Outils</li><li>Mises à jour</li></ul></div></div></div></section>

    <section className="bo-freedom light-section" data-motion-section><div className="site-container"><div className="bo-heading-row" data-reveal><p className="section-index">08 / ACCOMPAGNEMENT</p><div><h2>Des outils pour <span>mieux vendre.</span></h2><p>Ces éléments sont prévus dans le parcours partenaire et restent indiqués comme en préparation tant qu'ils ne sont pas ouverts.</p></div></div><div className="bo-freedom-grid">{partnerSupport.map((item,index)=><article key={item.title} data-reveal><span>0{index+1}</span><h3>{item.title}</h3><p>{item.description}</p><em className="bo-feature-status">En préparation</em></article>)}</div></div></section>

    <section className="bo-faq light-section" data-motion-section><div className="site-container bo-faq-layout"><div className="bo-faq-heading" data-reveal><p className="section-index">09 / QUESTIONS</p><h2>Construisez votre activité. <span>WALS fournit la base.</span></h2></div><div className="bo-faq-list" data-reveal>{partnerFaq.map(([question,answer])=><details key={question}><summary>{question}<span>+</span></summary><p>{answer}</p></details>)}</div></div></section>

    <section id="ouverture" className="bo-final" data-motion-section><div className="bo-final-grid"/><div className="site-container bo-final-layout"><div data-reveal><div className="bo-dev-note is-light"><i/> Accès partenaires en préparation</div><h2>Votre prochaine offre <span>peut commencer ici.</span></h2><p>Présentez votre activité et la manière dont vous souhaitez proposer WALS.</p><div className="bo-final-proof"><CheckIcon/> La demande ne vous inscrit pas automatiquement aux communications marketing.</div></div><div className="bo-final-form" data-reveal><small>PROGRAMME PARTENAIRE</small><h3>Demander l'accès</h3><LeadForm audience="partner"/></div></div></section>
  </main><SiteFooter/></div>;
}
